### ISSUE TITLE
Came here from your VSCode setup guide

### ISSUE THREAD

**Issue by bleuge** [fredrikaverpil/dotfiles#1]
Did you stop using it? 
Thanks!

**Comment by fredrikaverpil** [comment]
Hi @bleuge no, I did not stop using vscode. It's my no. 1 editor of choice. Why do you ask?

That [setup guide](https://fredrikaverpil.github.io/2017/02/02/my-vscode-setup/) is quite old, actually.

**Comment by bleuge** [comment]
It was a very good guide, but outdated as you said, I wondered if you had it updated somewhere, thanks anyways, I was trying to build a Freepascal complete development installation, portable. 
Thanks!
